server:
   port: 8000
   context-path: /wpfc
my:
  uuid: ${random.uuid}

#default dateSource: org.apache.tomcat.jdbc.pool.DataSource
spring: 
   datasource: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/boot
      username: root
      password: 123456
      
   #Spring MVC view prefix/suffix 
   mvc: 
     view: 
        prefix: /WEB-INF/jsp/
        suffix: .jsp
       
##Ĭ������������Ч,�޴�������ͨ����������MapperScanɨ��xml
mybatis:
   typeAliasesPackage: cn.edu.ntu.entity
   mapper-locations: classpath:mappers/*.xml

#log
logging: 
   level: 
      org: 
        apache.ibatis: debug
        springframework.web: debug
      cn.edu.ntu: debug